http:
  routers:
    backend:
      rule: "Host(`journal.sachethkoushal.tech`) && PathPrefix(`/api`)"
      service: backend
      entryPoints:
        - web
    frontend:
      rule: "Host(`journal.sachethkoushal.tech`)"
      service: frontend
      entryPoints:
        - web

  services:
    backend:
      loadBalancer:
        servers:
          - url: "http://backend:3001"
    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:3000"
